In [2]:
import numpy as np

In [9]:
arr = np.arange(10, 50)
np.flip(arr)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
arr = np.arange(1, 25)
arr.reshape(4, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [70]:
result = arr[(arr >= 10) & (arr <= 20)]
result

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])