In [5]:
import numpy as np

In [11]:
# 1
arr = np.arange(1, 11)
print(arr)
print('ndim:', arr.ndim)
print(arr.shape)
print(arr.dtype)
print('size:', np.size(arr))

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
(10,)
int64
size: 10


In [ ]:
# 2-1

In [ ]:

# 2-2
randomNum = np.random.random((1, 10))
print(randomNum)

maxValue = randomNum.max()
minValue = randomNum.min()

print(maxValue)
print(minValue)

[[0.25921277 0.10343823 0.48688625 0.73949384 0.39863397 0.23307442
  0.07639862 0.76163903 0.43041134 0.4265623 ]]
0.7616390263778101
0.07639861690947014


In [21]:
# 2-3 
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 2-4
arrShape = np.arange(1, 25).reshape((4, 6))
print(arr)

# 2-5
print(arrShape[1:3, 1:5])

# 2-6
print(arrShape[2:, ::-1])



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 8  9 10 11]
 [14 15 16 17]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


NameError: name 'arrShape' is not defined