In [2]:
import numpy as np

In [5]:
# 3
arr = np.arange(1,21)
print(arr[-1])
print(arr.sum())
print(arr.mean()) # 평균

new_arr = arr.reshape(5, 4)
print(new_arr)

20
210
10.5
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [6]:
# 4
salary = [200, 150, 180, 220, 250]
new_salary = np.array(salary, dtype = 'float64' ) * 1.5
print('인상 금액: ', new_salary)
avg_salary = np.mean(new_salary)
print('평균 금액: ', avg_salary)
result = new_salary >= avg_salary
print('평균 이상 원소: ', new_salary[result])
print('평균 이상인 원소 갯수: ', new_salary)

인상 금액:  [300. 225. 270. 330. 375.]
평균 금액:  300.0
평균 이상 원소:  [300. 330. 375.]
평균 이상인 원소 갯수:  [300. 225. 270. 330. 375.]
