In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print([1, 2, 3, 4, 5])

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[1, 2, 3], [4, 5, 6]], 
                [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.zeros(10) # 0으로 구성된 배열
print(a) # ,가 아닌 . 으로 구별

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
b = np.ones((3, 3)) # 3X3 이차원 배열, 1로 채움
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
c = np.full((3, 3), 9) # 9로 채움
print(c)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
d = np.eye(3) # 단위 행렬
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arange = np.arange(1, 21) # 21 미만까지
print(arange)

arange2 = np.arange(1, 21, 3) # 3칸씩
print(arange2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  4  7 10 13 16 19]


In [14]:
# 데이터분석 = 통계 / 그래프(구간, 균등 간격)
lin = np.linspace(0, 10, 3)
print(lin)

[ 0.  5. 10.]


In [ ]:
rr = np.random.random() # 0에서 1 사이의 균등 분포에서 표본 추출
print(rr)

rr2 = np.random.random((4, 4)) # 4X4 이차원 배열 형태
print(rr2)

0.2952114884250776
[[0.38371972 0.87478476 0.47418284 0.36347966]
 [0.59923545 0.68855725 0.57849944 0.53684557]
 [0.65039447 0.20599439 0.89314588 0.59517054]
 [0.55610004 0.38246553 0.43651121 0.57011419]]


In [ ]:
ranInt = np.random.randint(1, 10) # 1~10 사이
print(ranInt)

ranInt2 = np.random.randint(1, 10, (4, 4)) # 4X4 배열 사이즈
print(ranInt2)

6
[[8 6 3 8]
 [7 1 3 6]
 [2 4 5 3]
 [2 4 7 3]]


In [ ]:
a = np.arange(11)
print(a)

print(a[a<5])
print(a[a%2 == 0])

five_up = (a > 5)
print(a[five_up])

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[ 0  2  4  6  8 10]
[ 6  7  8  9 10]


In [ ]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

# 합 구하기
print(a.sum())
print(np.sum(a))

b = a.sum(axis=0) # 각 열의 합
print(b)

c= a.sum(axis=1) # 각 행의 합
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
45
[12 15 18]
[ 6 15 24]


In [11]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 1, 1, 1, 1])
print(x + y)

y = 1
print(x + y)

[2 3 4 5 6]
[2 3 4 5 6]


In [14]:
a = np.arange(1, 25).reshape(4, 6)
print(a + 100) # 브로드 캐스팅

# 스칼라 배열 변경
new_arr = np.full_like(a, 100)
print(new_arr)

# 배열 이항 연산
print(a + new_arr)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [15]:
a = np.arange(5).reshpae((1, 5))
print(a)
b = np.arange(5).reshape((5, 1))
print(b)

print(a + b)

AttributeError: 'numpy.ndarray' object has no attribute 'reshpae'